name: lifestealcore
version: "${version}"
main: com.spectrasonic.lifestealcore.Main
api-version: "1.21"
authors: [Spectrasonic]
commands:
    lifesteal:
        description: Comandos de LifeSteal
        usage: /<command> <add|remove|reload> <cantidad> [jugador]
        aliases: [ls]
    revive:
        description: Revive a un jugador
        usage: /<command> <jugador>
        aliases: [rv]
        permission: lifesteal.revive
permissions:
    lifesteal.admin:
        default: op
    lifesteal.help:
        default: op
    lifesteal.revive:
        default: op
